#!/usr/bin/perl

use English; 
my $A="~/.server_aliases_ixtens"; 
my $B=@ARGV[0]; 
my $C=`cat $A | grep "${B}="`; 


$C =~ s/.+?ssh/\\/s; 
#print $C;
#$C =~ /([0-9a-zA-Z\.]+)/ ; 

$C =~ /([[:alnum:]\.]+)/ ;

print "$1\n";
#print "Pre :\t$`\nMatch :\t$&\nPost :\t$'\n"; 