#!/bin/bash            
# sha-bang is needed to have syntax highlighting in various editors

function __wget_make_proxy_vars(){
        export `env | egrep -i 'wget(.+?)proxy' | sed 's/wget_//g'`     # Pick a 'wget_<protocol>_proxy' and re-export as <protocol>_proxy
                                                                        # Also would ingest wget_no_proxy and re-export as no_proxy
}

function wget(){
	wget -c -T 10 -t 0 "$@"
}
